const END_POINTS = {
  LOGIN: "api/user/login",
  REGISTER: "api/user/register",
  LOGOUT: "api/user/logout",
  VERIFY_OTP: "api/user/verify-otp",
  RESEND_OTP: "api/user/resend-otp",
  ADMIN_LOGIN: "api/admin/login",
  ADMIN_REGISTER: "api/admin/register",
  ADMIN_LOGOUT: "api/admin/logout",
  ADMIN_VERIFY_OTP: "api/admin/verify-otp",
  ADMIN_PENDING_REQUESTS: "api/admin/pending-admin-requests",
  APPROVE_ADMIN_REQUEST: "api/admin/approve-admin-request",
  REJECT_ADMIN_REQUEST: "api/admin/reject-admin-request",
  LOAD_COMPETITIONS: 'api/admin/competitions',
  ADD_COMPETITION: "api/admin/add-Competitions",
  EDIT_COMPETITION: "api/admin/edit-competition",
  DELETE_COMPETITION: "api/admin/delete-competition",
  LOAD_TREKKINGS: "api/admin/trekking",
  ADD_TREKKING: "api/admin/add-trekking",
  EDIT_TREKKING: "api/admin/edit-trekking",
  DELETE_TREKKING: "api/admin/delete-trekking",
  ADD_CATEGORY: "api/admin/add-product-category",
  EDIT_CATEGORY: "api/admin/edit-product-categories",
  TOGGLE_CATEGORY: "api/admin/product-categories-toggle",
  LOAD_CATEGORIES: "api/admin/product-categories",
  ADD_PRODUCT: "api/admin/add-product",
  EDIT_PRODUCT: "api/admin/edit-product",
  TOGGLE_PRODUCT: "api/admin/product",
  LOAD_PRODUCTS: "api/admin/products",
  USERLIST: "api/admin/users",
  LOAD_USER_PRODUCTS: "api/user/products",
  LOAD_SHOP_PRODUCTS: "api/user/shop-products",
  LOAD_PRODUCT_DETAILS: "api/user/products",
  ADD_TO_CART: "api/user/cart",
  LOAD_CART: "api/user/cart",
  UPDATE_CART_QUANTITY: "api/user/cart",
  LOAD_USER_COMPETITIONS: "api/user/competitions",
  LOAD_USER_COMPETITION_DETAILS: 'api/user/competition-Details',
  REGISTER_COMPETITION: "api/user/registerForCompetition",
  Fetch_Payment_Details: "api/user/showPaymentConfirmation",
  LOAD_USER_TREKKINGS: "api/user/trekkings",
  UPDATE_USER:"api/user/updateProfile",
  LOAD_ADDRESSES: "api/user/addresses",
  ADD_ADDRESS: "api/user/add-address",
  UPDATE_ADDRESS: "api/user/update-address",
  DELETE_ADDRESS: "api/user/delete-address",
  
};
export default END_POINTS;
